### ISSUE TITLE
Every XSLT File has a superfluous "</xsl:for-each>" element

### ISSUE THREAD

**Issue by karstenw** [GoyaPtyLtd/BaseElements-DDR-XSLT#1]
Each of the four XSLT files has a closing "</xsl:for-each>" element too many.

**Comment by nickorr** [comment]
Karsten,

Thanks, I've fixed these and updated.  I've got files for other all the other data too if you're interested - I just hadn't got around to uploading them all.  Let me know what you're looking at or working on.

Cheers,
Nick

**Comment by karstenw** [comment]
Yes, please.

Just because I believe there should be an open source DDR-XSLT for those who forge their own tools.

**Comment by karstenw** [comment]
All 4 xslt can be used for XML import.
